apiVersion: v1
kind: Service
metadata:
  labels:
    run: findafont
  name: findafont
  namespace: wstech
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: api
    port: 9000
    protocol: TCP
  selector:
    app: findafont
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: findafont
  namespace: wstech
spec:
  rules:
  - host: faf.api.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: findafont
            port:
              name: http
      - path: /api/deploy
        pathType: Exact
        backend:
          service:
            name: findafont
            port:
              name: api
